version: '3'

services:
  db:
      image: postgres:10.4
      expose:
        - 5432
      volumes:
        - pg_data:/var/lib/postgresql/data
        - pg_backups:/pg_backups
      environment:
        - POSTGRES_USER=shorterdb
        - POSTGRES_PASSWORD=shorterdb
        - POSTGRES_DB=shorterdb

  backend:
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - "80:8000"
        - "443:8000"
      volumes:
        - static-files:/data

volumes:
  static-files:
  pg_data: {}
  pg_backups: {}